### ISSUE TITLE
BUG001: Definición- Error de ortografía "sptints" en el texto

### ISSUE THREAD

**Issue by adrimonroy** [cthproj/Certificatech#10]
Descripcion:

1. Se ingresa a Menu>Conceptos generales>Definición de Scrum
2. Se observa la interfaz con el texto 

Error: Dentro del texto se observa " basados en la comunicación clara y transparente acerca de los procesos que se vayan realizando en cada uno de los **sptints** del proyecto"

Funcionamiento esperado: Se debe visualizar la palabra resaltada como "Sprints"
[bug001_Definicion.xlsx](https://github.com/cthproj/Certificatech/files/2078719/bug001_Definicion.xlsx)

**Comment by GioPetrucci** [comment]
Evidencia Bug corregido:
![image](https://user-images.githubusercontent.com/23438518/42119529-aa7c1e3c-7bd2-11e8-9d15-3aff97a72bcf.png)
