### ISSUE TITLE
BUG002- Fases de Scrum: Los  popups no contienen el título a que proceso de la fase corresponden

### ISSUE THREAD

**Issue by adrimonroy** [cthproj/Certificatech#11]
Descripción: 

1. Se ingresa a Menu>Conceptos generales>Fases de scrum
2. Elija cualquiera de los procesos del 2-18
3.Se despliega el popup

Error: No se visualiza el titulo del proceso al que pertenece el popup.
[002_Fases Scrum.xlsx](https://github.com/cthproj/Certificatech/files/2082712/002_Fases.Scrum.xlsx)

**Comment by GioPetrucci** [comment]
Corrección del bug:
![image](https://user-images.githubusercontent.com/23438518/42119840-4b215a34-7bd6-11e8-8682-46440225118a.png)
