### ISSUE TITLE
BUG003 - Control del proceso Empírico: frase "día" mal escrita

### ISSUE THREAD

**Issue by adrimonroy** [cthproj/Certificatech#12]
Descripción: 

1. Se ingresa a Menú>Principios de Scrum>Control del proceso empírico
2. Se despliega la pagina seleccionada con el texto

Error: dentro del texto se visualiza "Reuniones diarias: donde se informa acerca de avances desde el día anterior, la planificación para el **dia** actual y los inconvenientes diarios que puedan impactar el sprint."

Funcionamiento esperado: se debe visualizar la palabra **Día** correctamente.
[003_Principios_Ctrl proc empirico.xlsx](https://github.com/cthproj/Certificatech/files/2082747/003_Principios_Ctrl.proc.empirico.xlsx)

**Comment by GioPetrucci** [comment]
Bug Fixing Evidence:
![image](https://user-images.githubusercontent.com/23438518/42120014-caa05190-7bd9-11e8-9b31-579c5f5f99a6.png)
