### ISSUE TITLE
BUG004 - Principios- Control del proceso empírico : Tipo de letra 

### ISSUE THREAD

**Issue by adrimonroy** [cthproj/Certificatech#13]
Descripción: 

1. Se ingresa a Menú>Principios de Scrum>Control del proceso empírico
2. Se visualiza el texto

Error: se observa texto en 2 tipos de letra diferente
[004_Principios_Ctrl proc empirico_letra.xlsx](https://github.com/cthproj/Certificatech/files/2082806/004_Principios_Ctrl.proc.empirico_letra.xlsx)

Funcionamiento esperado: La letra debe ser de un solo tipo para que se vea uniforme.

**Comment by GioPetrucci** [comment]
@adrimonroy El defecto hace referencia a que el tipo de letra del título debe ser igual que el texto o los encabezados de la columna izquierda?
![image](https://user-images.githubusercontent.com/23438518/42120614-d322abd8-7be3-11e8-8492-96e12ac0ca48.png)

**Comment by adrimonroy** [comment]
@GioPetrucci Hace referencia  a los títulos del cuadro.
