### ISSUE TITLE
BUG005-Priorización basa en valor- Título: El título se vsualiza alineado  a la izquierda

### ISSUE THREAD

**Issue by adrimonroy** [cthproj/Certificatech#14]
Descripcion: 

1. Se ingresa a Menú>Principios de Scrum>Priorización basada en valor
2. Se visualiza el título

Error: El título se ve alineado a la izquierda

Funcionamiento esperado: El titulo debe estar alineado al centro - se debe ver la barrita azul debajo
[005_Principios_Priorización basada en el valor.xlsx](https://github.com/cthproj/Certificatech/files/2147416/005_Principios_Priorizacion.basada.en.el.valor.xlsx)

**Comment by GioPetrucci** [comment]
Bug fixing evidence:
![image](https://user-images.githubusercontent.com/23438518/42120982-6abcc504-7bea-11e8-8927-c8485253220c.png)
