### ISSUE TITLE
BUG010-Aspectos - Organización: Tipo de letra

### ISSUE THREAD

**Issue by adrimonroy** [cthproj/Certificatech#19]
Descripción:

1. Se ingresa a Menú>Aspectos de Scrum>Organización
2. Se visualiza el texto de la interfaz

Error: Se visualiza el texto y en las tablas diferentes tipos de letra
Funcionamiento esperado: Se debe observar uniformidad en el texto y tablas de la interfaz.

[010_Aspectos_Organización.xlsx](https://github.com/cthproj/Certificatech/files/2147481/010_Aspectos_Organizacion.xlsx)

**Comment by GioPetrucci** [comment]
@adrimonroy Se intenta replicar, sin embargo tanto en ambiente local como en ambiente de pruebas se puede ver un sólo tipo de fuente, es probable que hubo un error en el CSS cuando se reportó. En caso de presentarse nuevamente el problema reabrir el bug.

**Comment by adrimonroy** [comment]
El error persiste.
