### ISSUE TITLE
BUG011- Aspectos - Organización: Imagen tipo de liderazgo tiene las uniones mal

### ISSUE THREAD

**Issue by adrimonroy** [cthproj/Certificatech#20]
Descripción: 

Descripción:

1.Se ingresa a Menú>Aspectos>Organización
2.Se ubica la imagen "Tipo de liderazgo"

Error: se observa la imagen con sus lineas de unión deshechas

Funcionamiento esperado: Se debe poder visualizar la imagen con todos sus componentes
[011_Aspectos_Organización_Imagen.xlsx](https://github.com/cthproj/Certificatech/files/2147501/011_Aspectos_Organizacion_Imagen.xlsx)

**Comment by GioPetrucci** [comment]
Bug fixing evidence:
https://docs.google.com/document/d/1uTAl-ODCd0T8d-gjBemHw3h1emX6J_N4bdnhlNvR1W8/edit
