### ISSUE TITLE
BUG013 Aspectos-Organización: El enlace "Responsabilidades" no dirige a ninguna parte.

### ISSUE THREAD

**Issue by adrimonroy** [cthproj/Certificatech#22]
Descripción error: 

1. Se ingresa a Menú>Aspectos>Organización
2. Se ubica la tabla de "Roles Centrales"
3. Se ubica el rol "Propietario del producto"
4.Se hace clic en la palabra link "Responsabilidades"

Error: Permanece in movil en la interfaz, no dirige  ninguna interfaz.

Funcionamiento esperado: Al hacer clic sobre el link mencionado debe dirigir a la interfaz con las responsabilidades.
[013_Aspectos_Organización_Responsabilidades PO.xlsx](https://github.com/cthproj/Certificatech/files/2147519/013_Aspectos_Organizacion_Responsabilidades.PO.xlsx)

**Comment by GioPetrucci** [comment]
@adrimonroy Cuando se le da click a los enlaces de "Responsabilidades" te lleva a la tabla de roles y responsabilidades.
