### ISSUE TITLE
014-Aspectos: Los aspectos 2 a 5 no dirigen a la interfaz correspondiente a la consulta.

### ISSUE THREAD

**Issue by adrimonroy** [cthproj/Certificatech#23]
Descripción error: 

1.Se ingresa a Menú>Aspectos>Selecciona tipo de Aspecto del 2 al 5 

Error: No dirige a  ninguna interfaz permanece en la interfaz que está abierta.
Funcionamiento esperado: Debe dirigir a la interfaz correspondiente a la consulta realizada.
[014_Aspectos_Links Rotos.xlsx](https://github.com/cthproj/Certificatech/files/2147528/014_Aspectos_Links.Rotos.xlsx)

**Comment by GioPetrucci** [comment]
**Se agrega el enlace de los menús 2 y 3. Para cerrar este bug es necesario cerrar la US000**
